apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac8832-proj-pvc
spec:
  storageClassName: ibmc-vpc-block-5iops-tier
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi